### PR TITLE
Aesthetic changes

### PR DESCRIPTION
**Pull request by mmerlin6**
Hey, I really liked the modifications you made so I built off yours and made some minor aesthetic modifications. I figured I'd bring them to your attention.

Summary of changes:
Switched from using the ICOs for Pokémon to PNGs which have smaller file sizes and match the sprites used in the actual app
Added local time when Pokémon disappear (I found this useful while driving around to avoid needing to check the remaining time constantly)
Text cleanup

### CODE REVIEW

**Comment by mmerlin6** [comment]
Also, I noticed how you made the info window close after 5 seconds. This cleans up the clutter resulting from the clicking on multiple Pokémon which was previously a problem; however, when I am actively pursuing a specific Pokémon, I have to keep clicking on it since it keeps auto-closing.

I think it might be more user-friendly if it were to keep 1 info window open at a time. So, a window can be closed when the user taps anywhere else on the map (either another Pokémon or an empty space on the map) and when the Pokémon disappears. If you are interested, can you help implement it? I'm not good with Google Maps so I'm not sure where to start.

**Comment by JesseChrestler** [comment]
Thanks for your effort and great work, I will merge your changes. I agree with you that it's annoying to have to keep clicking, and I have an idea on how to make it happen.

**Comment by JesseChrestler** [comment]
Fixed

**Comment by mmerlin6** [comment]
It's perfect, thank you! It's now more intuitive when tracking down a target and also keeps it uncluttered.

**Pull request merged**
